onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - sharp
  - unrs-resolver

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  next@>=15.4.0-canary.0 <15.4.8: '>=15.4.8'
